// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_leagues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeReauthenticationTicket = `-- name: ConsumeReauthenticationTicket :one
UPDATE reauthentication_tickets AS tickets
SET consumed_at = now()
FROM sessions
WHERE tickets.token_hash = $2
  AND tickets.session_id = sessions.id
  AND sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.idle_expires_at > now()
  AND sessions.absolute_expires_at > now()
  AND tickets.consumed_at IS NULL
  AND tickets.expires_at > now()
RETURNING tickets.account_id
`

type ConsumeReauthenticationTicketParams struct {
	TokenHash   []byte
	TokenHash_2 []byte
}

func (q *Queries) ConsumeReauthenticationTicket(ctx context.Context, arg ConsumeReauthenticationTicketParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeReauthenticationTicket, arg.TokenHash, arg.TokenHash_2)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const consumeReauthenticationTicketAndRemovePassword = `-- name: ConsumeReauthenticationTicketAndRemovePassword :execrows
WITH consumed AS (
    UPDATE reauthentication_tickets AS tickets
    SET consumed_at = now()
    FROM sessions
    WHERE tickets.token_hash = $2
      AND tickets.session_id = sessions.id
      AND sessions.token_hash = $1
      AND sessions.revoked_at IS NULL
      AND sessions.idle_expires_at > now()
      AND sessions.absolute_expires_at > now()
      AND tickets.consumed_at IS NULL
      AND tickets.expires_at > now()
    RETURNING tickets.account_id
)
DELETE FROM local_credentials
WHERE account_id IN (SELECT account_id FROM consumed)
  AND EXISTS (
      SELECT 1 FROM external_identities
      WHERE external_identities.account_id = local_credentials.account_id
        AND external_identities.provider = 'google'
  )
`

type ConsumeReauthenticationTicketAndRemovePasswordParams struct {
	TokenHash   []byte
	TokenHash_2 []byte
}

func (q *Queries) ConsumeReauthenticationTicketAndRemovePassword(ctx context.Context, arg ConsumeReauthenticationTicketAndRemovePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeReauthenticationTicketAndRemovePassword, arg.TokenHash, arg.TokenHash_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeReauthenticationTicketAndSetPassword = `-- name: ConsumeReauthenticationTicketAndSetPassword :execrows
WITH consumed AS (
    UPDATE reauthentication_tickets AS tickets
    SET consumed_at = now()
    FROM sessions
    WHERE tickets.token_hash = $2
      AND tickets.session_id = sessions.id
      AND sessions.token_hash = $1
      AND sessions.revoked_at IS NULL
      AND sessions.idle_expires_at > now()
      AND sessions.absolute_expires_at > now()
      AND tickets.consumed_at IS NULL
      AND tickets.expires_at > now()
    RETURNING tickets.account_id
)
INSERT INTO local_credentials (account_id, password_hash)
SELECT account_id, $3 FROM consumed
ON CONFLICT (account_id) DO UPDATE SET password_hash = EXCLUDED.password_hash, updated_at = now()
`

type ConsumeReauthenticationTicketAndSetPasswordParams struct {
	TokenHash    []byte
	TokenHash_2  []byte
	PasswordHash string
}

func (q *Queries) ConsumeReauthenticationTicketAndSetPassword(ctx context.Context, arg ConsumeReauthenticationTicketAndSetPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeReauthenticationTicketAndSetPassword, arg.TokenHash, arg.TokenHash_2, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createReauthenticationTicket = `-- name: CreateReauthenticationTicket :one
INSERT INTO reauthentication_tickets (account_id, session_id, token_hash, expires_at)
SELECT sessions.account_id, sessions.id, $2, now() + interval '5 minutes'
FROM sessions
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.idle_expires_at > now()
  AND sessions.absolute_expires_at > now()
RETURNING id
`

type CreateReauthenticationTicketParams struct {
	TokenHash   []byte
	TokenHash_2 []byte
}

func (q *Queries) CreateReauthenticationTicket(ctx context.Context, arg CreateReauthenticationTicketParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createReauthenticationTicket, arg.TokenHash, arg.TokenHash_2)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findAuthenticatedAccountID = `-- name: FindAuthenticatedAccountID :one
SELECT sessions.account_id
FROM sessions
JOIN accounts ON accounts.id = sessions.account_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.idle_expires_at > now()
  AND sessions.absolute_expires_at > now()
  AND accounts.state = 'verified'
`

func (q *Queries) FindAuthenticatedAccountID(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAuthenticatedAccountID, tokenHash)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const followVisibleTournament = `-- name: FollowVisibleTournament :one
WITH visible_league AS (
    SELECT id
    FROM tournaments
    WHERE id = $1::uuid
      AND state IN ('published', 'in_progress', 'completed', 'cancelled')
), created_follow AS (
    INSERT INTO tournament_followers (tournament_id, account_id)
    SELECT id, $2::uuid
    FROM visible_league
    ON CONFLICT DO NOTHING
)
SELECT EXISTS (SELECT 1 FROM visible_league) AS visible
`

type FollowVisibleTournamentParams struct {
	TournamentID pgtype.UUID
	AccountID    pgtype.UUID
}

func (q *Queries) FollowVisibleTournament(ctx context.Context, arg FollowVisibleTournamentParams) (bool, error) {
	row := q.db.QueryRow(ctx, followVisibleTournament, arg.TournamentID, arg.AccountID)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const getAccessMethods = `-- name: GetAccessMethods :one
SELECT accounts.email, accounts.username,
  EXISTS (SELECT 1 FROM local_credentials WHERE account_id = accounts.id) AS has_password,
  EXISTS (SELECT 1 FROM external_identities WHERE account_id = accounts.id AND provider = 'google') AS has_google
FROM accounts
WHERE accounts.id = $1 AND accounts.state = 'verified'
`

type GetAccessMethodsRow struct {
	Email       string
	Username    string
	HasPassword bool
	HasGoogle   bool
}

func (q *Queries) GetAccessMethods(ctx context.Context, id pgtype.UUID) (GetAccessMethodsRow, error) {
	row := q.db.QueryRow(ctx, getAccessMethods, id)
	var i GetAccessMethodsRow
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.HasPassword,
		&i.HasGoogle,
	)
	return i, err
}

const getCurrentPasswordHash = `-- name: GetCurrentPasswordHash :one
SELECT local_credentials.password_hash
FROM sessions
JOIN local_credentials ON local_credentials.account_id = sessions.account_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.idle_expires_at > now()
  AND sessions.absolute_expires_at > now()
`

func (q *Queries) GetCurrentPasswordHash(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, getCurrentPasswordHash, tokenHash)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getCurrentSession = `-- name: GetCurrentSession :one
SELECT accounts.id, accounts.username, sessions.idle_expires_at, sessions.absolute_expires_at
FROM sessions
JOIN accounts ON accounts.id = sessions.account_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.idle_expires_at > now()
  AND sessions.absolute_expires_at > now()
  AND accounts.state = 'verified'
`

type GetCurrentSessionRow struct {
	ID                pgtype.UUID
	Username          string
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetCurrentSession(ctx context.Context, tokenHash []byte) (GetCurrentSessionRow, error) {
	row := q.db.QueryRow(ctx, getCurrentSession, tokenHash)
	var i GetCurrentSessionRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const listAdministeredTournaments = `-- name: ListAdministeredTournaments :many
SELECT
    tournaments.id,
    tournaments.name,
    tournaments.state,
    tournaments.created_at,
    tournaments.last_activity_at,
    CASE
        WHEN tournaments.organizer_account_id = $1::uuid THEN 'organizer'
        ELSE 'delegated'
    END AS relationship
FROM tournaments
LEFT JOIN tournament_administrators
    ON tournament_administrators.tournament_id = tournaments.id
    AND tournament_administrators.account_id = $1::uuid
WHERE (
    tournaments.organizer_account_id = $1::uuid
    OR tournament_administrators.account_id = $1::uuid
)
AND ($2::uuid IS NULL OR tournaments.id < $2::uuid)
ORDER BY tournaments.id DESC
LIMIT $3
`

type ListAdministeredTournamentsParams struct {
	AccountID pgtype.UUID
	CursorID  pgtype.UUID
	PageSize  int32
}

type ListAdministeredTournamentsRow struct {
	ID             pgtype.UUID
	Name           string
	State          string
	CreatedAt      pgtype.Timestamptz
	LastActivityAt pgtype.Timestamptz
	Relationship   string
}

func (q *Queries) ListAdministeredTournaments(ctx context.Context, arg ListAdministeredTournamentsParams) ([]ListAdministeredTournamentsRow, error) {
	rows, err := q.db.Query(ctx, listAdministeredTournaments, arg.AccountID, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdministeredTournamentsRow{}
	for rows.Next() {
		var i ListAdministeredTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.Relationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowedTournaments = `-- name: ListFollowedTournaments :many
SELECT
    tournaments.id,
    tournaments.name,
    tournaments.state,
    tournaments.created_at,
    tournaments.last_activity_at,
    'follower' AS relationship
FROM tournaments
JOIN tournament_followers ON tournament_followers.tournament_id = tournaments.id
WHERE tournament_followers.account_id = $1::uuid
  AND tournaments.organizer_account_id <> $1::uuid
  AND NOT EXISTS (
      SELECT 1
      FROM tournament_administrators
      WHERE tournament_administrators.tournament_id = tournaments.id
        AND tournament_administrators.account_id = $1::uuid
  )
  AND ($2::uuid IS NULL OR tournaments.id < $2::uuid)
ORDER BY tournaments.id DESC
LIMIT $3
`

type ListFollowedTournamentsParams struct {
	AccountID pgtype.UUID
	CursorID  pgtype.UUID
	PageSize  int32
}

type ListFollowedTournamentsRow struct {
	ID             pgtype.UUID
	Name           string
	State          string
	CreatedAt      pgtype.Timestamptz
	LastActivityAt pgtype.Timestamptz
	Relationship   string
}

func (q *Queries) ListFollowedTournaments(ctx context.Context, arg ListFollowedTournamentsParams) ([]ListFollowedTournamentsRow, error) {
	rows, err := q.db.Query(ctx, listFollowedTournaments, arg.AccountID, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowedTournamentsRow{}
	for rows.Next() {
		var i ListFollowedTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.Relationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAccountTournaments = `-- name: ListRecentAccountTournaments :many
WITH related_tournaments AS (
    SELECT
        tournaments.id,
        tournaments.name,
        tournaments.state,
        tournaments.created_at,
        tournaments.last_activity_at,
        CASE
            WHEN tournaments.organizer_account_id = $1::uuid THEN 'organizer'
            ELSE 'delegated'
        END AS relationship
    FROM tournaments
    LEFT JOIN tournament_administrators
        ON tournament_administrators.tournament_id = tournaments.id
        AND tournament_administrators.account_id = $1::uuid
    WHERE tournaments.organizer_account_id = $1::uuid
       OR tournament_administrators.account_id = $1::uuid

    UNION ALL

    SELECT
        tournaments.id,
        tournaments.name,
        tournaments.state,
        tournaments.created_at,
        tournaments.last_activity_at,
        'follower' AS relationship
    FROM tournaments
    JOIN tournament_followers ON tournament_followers.tournament_id = tournaments.id
    WHERE tournament_followers.account_id = $1::uuid
      AND tournaments.organizer_account_id <> $1::uuid
      AND NOT EXISTS (
          SELECT 1
          FROM tournament_administrators
          WHERE tournament_administrators.tournament_id = tournaments.id
            AND tournament_administrators.account_id = $1::uuid
      )
)
SELECT id, name, state, created_at, last_activity_at, relationship
FROM related_tournaments
ORDER BY last_activity_at DESC, id DESC
LIMIT 5
`

type ListRecentAccountTournamentsRow struct {
	ID             pgtype.UUID
	Name           string
	State          string
	CreatedAt      pgtype.Timestamptz
	LastActivityAt pgtype.Timestamptz
	Relationship   string
}

func (q *Queries) ListRecentAccountTournaments(ctx context.Context, accountID pgtype.UUID) ([]ListRecentAccountTournamentsRow, error) {
	rows, err := q.db.Query(ctx, listRecentAccountTournaments, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentAccountTournamentsRow{}
	for rows.Next() {
		var i ListRecentAccountTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.Relationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :execrows
WITH revoked_session AS (
    UPDATE sessions
    SET revoked_at = now()
    WHERE sessions.token_hash = $1
      AND sessions.revoked_at IS NULL
      AND sessions.idle_expires_at > now()
      AND sessions.absolute_expires_at > now()
    RETURNING id
)
UPDATE session_refresh_tokens
SET revoked_at = now()
WHERE session_id IN (SELECT id FROM revoked_session)
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unfollowTournament = `-- name: UnfollowTournament :exec
DELETE FROM tournament_followers
WHERE tournament_id = $1::uuid
  AND account_id = $2::uuid
`

type UnfollowTournamentParams struct {
	TournamentID pgtype.UUID
	AccountID    pgtype.UUID
}

func (q *Queries) UnfollowTournament(ctx context.Context, arg UnfollowTournamentParams) error {
	_, err := q.db.Exec(ctx, unfollowTournament, arg.TournamentID, arg.AccountID)
	return err
}
