// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_leagues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAuthenticatedAccountID = `-- name: FindAuthenticatedAccountID :one
SELECT sessions.account_id
FROM sessions
JOIN accounts ON accounts.id = sessions.account_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.idle_expires_at > now()
  AND sessions.absolute_expires_at > now()
  AND accounts.state = 'verified'
`

func (q *Queries) FindAuthenticatedAccountID(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAuthenticatedAccountID, tokenHash)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const followVisibleLeague = `-- name: FollowVisibleLeague :one
WITH visible_league AS (
    SELECT id
    FROM leagues
    WHERE id = $1::uuid
      AND state <> 'draft'
), created_follow AS (
    INSERT INTO league_followers (league_id, account_id)
    SELECT id, $2::uuid
    FROM visible_league
    ON CONFLICT DO NOTHING
)
SELECT EXISTS (SELECT 1 FROM visible_league) AS visible
`

type FollowVisibleLeagueParams struct {
	LeagueID  pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) FollowVisibleLeague(ctx context.Context, arg FollowVisibleLeagueParams) (bool, error) {
	row := q.db.QueryRow(ctx, followVisibleLeague, arg.LeagueID, arg.AccountID)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const listAdministeredLeagues = `-- name: ListAdministeredLeagues :many
SELECT
    leagues.id,
    leagues.name,
    leagues.state,
    leagues.created_at,
    CASE
        WHEN leagues.organizer_account_id = $1::uuid THEN 'organizer'
        ELSE 'delegated'
    END AS relationship
FROM leagues
LEFT JOIN league_administrators
    ON league_administrators.league_id = leagues.id
    AND league_administrators.account_id = $1::uuid
WHERE (
    leagues.organizer_account_id = $1::uuid
    OR league_administrators.account_id = $1::uuid
)
AND ($2::uuid IS NULL OR leagues.id < $2::uuid)
ORDER BY leagues.id DESC
LIMIT $3
`

type ListAdministeredLeaguesParams struct {
	AccountID pgtype.UUID
	CursorID  pgtype.UUID
	PageSize  int32
}

type ListAdministeredLeaguesRow struct {
	ID           pgtype.UUID
	Name         string
	State        string
	CreatedAt    pgtype.Timestamptz
	Relationship string
}

func (q *Queries) ListAdministeredLeagues(ctx context.Context, arg ListAdministeredLeaguesParams) ([]ListAdministeredLeaguesRow, error) {
	rows, err := q.db.Query(ctx, listAdministeredLeagues, arg.AccountID, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdministeredLeaguesRow{}
	for rows.Next() {
		var i ListAdministeredLeaguesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.CreatedAt,
			&i.Relationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowedLeagues = `-- name: ListFollowedLeagues :many
SELECT
    leagues.id,
    leagues.name,
    leagues.state,
    leagues.created_at,
    'follower' AS relationship
FROM leagues
JOIN league_followers ON league_followers.league_id = leagues.id
WHERE league_followers.account_id = $1::uuid
  AND leagues.organizer_account_id <> $1::uuid
  AND NOT EXISTS (
      SELECT 1
      FROM league_administrators
      WHERE league_administrators.league_id = leagues.id
        AND league_administrators.account_id = $1::uuid
  )
  AND ($2::uuid IS NULL OR leagues.id < $2::uuid)
ORDER BY leagues.id DESC
LIMIT $3
`

type ListFollowedLeaguesParams struct {
	AccountID pgtype.UUID
	CursorID  pgtype.UUID
	PageSize  int32
}

type ListFollowedLeaguesRow struct {
	ID           pgtype.UUID
	Name         string
	State        string
	CreatedAt    pgtype.Timestamptz
	Relationship string
}

func (q *Queries) ListFollowedLeagues(ctx context.Context, arg ListFollowedLeaguesParams) ([]ListFollowedLeaguesRow, error) {
	rows, err := q.db.Query(ctx, listFollowedLeagues, arg.AccountID, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowedLeaguesRow{}
	for rows.Next() {
		var i ListFollowedLeaguesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.CreatedAt,
			&i.Relationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowLeague = `-- name: UnfollowLeague :exec
DELETE FROM league_followers
WHERE league_id = $1::uuid
  AND account_id = $2::uuid
`

type UnfollowLeagueParams struct {
	LeagueID  pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) UnfollowLeague(ctx context.Context, arg UnfollowLeagueParams) error {
	_, err := q.db.Exec(ctx, unfollowLeague, arg.LeagueID, arg.AccountID)
	return err
}
