// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_leagues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeReauthenticationTicket = `-- name: ConsumeReauthenticationTicket :one
UPDATE reauthentication_tickets AS tickets
SET consumed_at = now()
FROM sessions
WHERE tickets.token_hash = $2
  AND tickets.session_id = sessions.id
  AND sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.idle_expires_at > now()
  AND sessions.absolute_expires_at > now()
  AND tickets.consumed_at IS NULL
  AND tickets.expires_at > now()
RETURNING tickets.account_id
`

type ConsumeReauthenticationTicketParams struct {
	TokenHash   []byte
	TokenHash_2 []byte
}

func (q *Queries) ConsumeReauthenticationTicket(ctx context.Context, arg ConsumeReauthenticationTicketParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeReauthenticationTicket, arg.TokenHash, arg.TokenHash_2)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const consumeReauthenticationTicketAndSetPassword = `-- name: ConsumeReauthenticationTicketAndSetPassword :execrows
WITH consumed AS (
    UPDATE reauthentication_tickets AS tickets
    SET consumed_at = now()
    FROM sessions
    WHERE tickets.token_hash = $2
      AND tickets.session_id = sessions.id
      AND sessions.token_hash = $1
      AND sessions.revoked_at IS NULL
      AND sessions.idle_expires_at > now()
      AND sessions.absolute_expires_at > now()
      AND tickets.consumed_at IS NULL
      AND tickets.expires_at > now()
    RETURNING tickets.account_id
)
INSERT INTO local_credentials (account_id, password_hash)
SELECT account_id, $3 FROM consumed
ON CONFLICT (account_id) DO UPDATE SET password_hash = EXCLUDED.password_hash, updated_at = now()
`

type ConsumeReauthenticationTicketAndSetPasswordParams struct {
	TokenHash    []byte
	TokenHash_2  []byte
	PasswordHash string
}

func (q *Queries) ConsumeReauthenticationTicketAndSetPassword(ctx context.Context, arg ConsumeReauthenticationTicketAndSetPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeReauthenticationTicketAndSetPassword, arg.TokenHash, arg.TokenHash_2, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createReauthenticationTicket = `-- name: CreateReauthenticationTicket :one
INSERT INTO reauthentication_tickets (account_id, session_id, token_hash, expires_at)
SELECT sessions.account_id, sessions.id, $2, now() + interval '5 minutes'
FROM sessions
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.idle_expires_at > now()
  AND sessions.absolute_expires_at > now()
RETURNING id
`

type CreateReauthenticationTicketParams struct {
	TokenHash   []byte
	TokenHash_2 []byte
}

func (q *Queries) CreateReauthenticationTicket(ctx context.Context, arg CreateReauthenticationTicketParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createReauthenticationTicket, arg.TokenHash, arg.TokenHash_2)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findAuthenticatedAccountID = `-- name: FindAuthenticatedAccountID :one
SELECT sessions.account_id
FROM sessions
JOIN accounts ON accounts.id = sessions.account_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.idle_expires_at > now()
  AND sessions.absolute_expires_at > now()
  AND accounts.state = 'verified'
`

func (q *Queries) FindAuthenticatedAccountID(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAuthenticatedAccountID, tokenHash)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const followVisibleLeague = `-- name: FollowVisibleLeague :one
WITH visible_league AS (
    SELECT id
    FROM leagues
    WHERE id = $1::uuid
      AND state IN ('published', 'in_progress', 'completed', 'cancelled')
), created_follow AS (
    INSERT INTO league_followers (league_id, account_id)
    SELECT id, $2::uuid
    FROM visible_league
    ON CONFLICT DO NOTHING
)
SELECT EXISTS (SELECT 1 FROM visible_league) AS visible
`

type FollowVisibleLeagueParams struct {
	LeagueID  pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) FollowVisibleLeague(ctx context.Context, arg FollowVisibleLeagueParams) (bool, error) {
	row := q.db.QueryRow(ctx, followVisibleLeague, arg.LeagueID, arg.AccountID)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const getAccessMethods = `-- name: GetAccessMethods :one
SELECT accounts.email, accounts.username,
  EXISTS (SELECT 1 FROM local_credentials WHERE account_id = accounts.id) AS has_password,
  EXISTS (SELECT 1 FROM external_identities WHERE account_id = accounts.id AND provider = 'google') AS has_google
FROM accounts
WHERE accounts.id = $1 AND accounts.state = 'verified'
`

type GetAccessMethodsRow struct {
	Email       string
	Username    string
	HasPassword bool
	HasGoogle   bool
}

func (q *Queries) GetAccessMethods(ctx context.Context, id pgtype.UUID) (GetAccessMethodsRow, error) {
	row := q.db.QueryRow(ctx, getAccessMethods, id)
	var i GetAccessMethodsRow
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.HasPassword,
		&i.HasGoogle,
	)
	return i, err
}

const getCurrentPasswordHash = `-- name: GetCurrentPasswordHash :one
SELECT local_credentials.password_hash
FROM sessions
JOIN local_credentials ON local_credentials.account_id = sessions.account_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.idle_expires_at > now()
  AND sessions.absolute_expires_at > now()
`

func (q *Queries) GetCurrentPasswordHash(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, getCurrentPasswordHash, tokenHash)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const listAdministeredLeagues = `-- name: ListAdministeredLeagues :many
SELECT
    leagues.id,
    leagues.name,
    leagues.state,
    leagues.created_at,
    CASE
        WHEN leagues.organizer_account_id = $1::uuid THEN 'organizer'
        ELSE 'delegated'
    END AS relationship
FROM leagues
LEFT JOIN league_administrators
    ON league_administrators.league_id = leagues.id
    AND league_administrators.account_id = $1::uuid
WHERE (
    leagues.organizer_account_id = $1::uuid
    OR league_administrators.account_id = $1::uuid
)
AND ($2::uuid IS NULL OR leagues.id < $2::uuid)
ORDER BY leagues.id DESC
LIMIT $3
`

type ListAdministeredLeaguesParams struct {
	AccountID pgtype.UUID
	CursorID  pgtype.UUID
	PageSize  int32
}

type ListAdministeredLeaguesRow struct {
	ID           pgtype.UUID
	Name         string
	State        string
	CreatedAt    pgtype.Timestamptz
	Relationship string
}

func (q *Queries) ListAdministeredLeagues(ctx context.Context, arg ListAdministeredLeaguesParams) ([]ListAdministeredLeaguesRow, error) {
	rows, err := q.db.Query(ctx, listAdministeredLeagues, arg.AccountID, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdministeredLeaguesRow{}
	for rows.Next() {
		var i ListAdministeredLeaguesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.CreatedAt,
			&i.Relationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowedLeagues = `-- name: ListFollowedLeagues :many
SELECT
    leagues.id,
    leagues.name,
    leagues.state,
    leagues.created_at,
    'follower' AS relationship
FROM leagues
JOIN league_followers ON league_followers.league_id = leagues.id
WHERE league_followers.account_id = $1::uuid
  AND leagues.organizer_account_id <> $1::uuid
  AND NOT EXISTS (
      SELECT 1
      FROM league_administrators
      WHERE league_administrators.league_id = leagues.id
        AND league_administrators.account_id = $1::uuid
  )
  AND ($2::uuid IS NULL OR leagues.id < $2::uuid)
ORDER BY leagues.id DESC
LIMIT $3
`

type ListFollowedLeaguesParams struct {
	AccountID pgtype.UUID
	CursorID  pgtype.UUID
	PageSize  int32
}

type ListFollowedLeaguesRow struct {
	ID           pgtype.UUID
	Name         string
	State        string
	CreatedAt    pgtype.Timestamptz
	Relationship string
}

func (q *Queries) ListFollowedLeagues(ctx context.Context, arg ListFollowedLeaguesParams) ([]ListFollowedLeaguesRow, error) {
	rows, err := q.db.Query(ctx, listFollowedLeagues, arg.AccountID, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowedLeaguesRow{}
	for rows.Next() {
		var i ListFollowedLeaguesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.CreatedAt,
			&i.Relationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :execrows
WITH revoked_session AS (
    UPDATE sessions
    SET revoked_at = now()
    WHERE sessions.token_hash = $1
      AND sessions.revoked_at IS NULL
      AND sessions.idle_expires_at > now()
      AND sessions.absolute_expires_at > now()
    RETURNING id
)
UPDATE session_refresh_tokens
SET revoked_at = now()
WHERE session_id IN (SELECT id FROM revoked_session)
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unfollowLeague = `-- name: UnfollowLeague :exec
DELETE FROM league_followers
WHERE league_id = $1::uuid
  AND account_id = $2::uuid
`

type UnfollowLeagueParams struct {
	LeagueID  pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) UnfollowLeague(ctx context.Context, arg UnfollowLeagueParams) error {
	_, err := q.db.Exec(ctx, unfollowLeague, arg.LeagueID, arg.AccountID)
	return err
}
