// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apple.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAppleCallback = `-- name: ClaimAppleCallback :one
UPDATE apple_login_challenges SET callback_claimed_at = now()
WHERE state_hash = $1 AND callback_claimed_at IS NULL AND expires_at > now()
RETURNING id, nonce_hash, platform
`

type ClaimAppleCallbackRow struct {
	ID        pgtype.UUID
	NonceHash []byte
	Platform  string
}

func (q *Queries) ClaimAppleCallback(ctx context.Context, stateHash []byte) (ClaimAppleCallbackRow, error) {
	row := q.db.QueryRow(ctx, claimAppleCallback, stateHash)
	var i ClaimAppleCallbackRow
	err := row.Scan(&i.ID, &i.NonceHash, &i.Platform)
	return i, err
}

const completeAppleCallback = `-- name: CompleteAppleCallback :execrows
UPDATE apple_login_challenges SET subject = $2, email = $3, email_verified = $4
WHERE id = $1 AND callback_claimed_at IS NOT NULL AND subject IS NULL AND expires_at > now()
`

type CompleteAppleCallbackParams struct {
	ID            pgtype.UUID
	Subject       pgtype.Text
	Email         pgtype.Text
	EmailVerified bool
}

func (q *Queries) CompleteAppleCallback(ctx context.Context, arg CompleteAppleCallbackParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAppleCallback,
		arg.ID,
		arg.Subject,
		arg.Email,
		arg.EmailVerified,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeAppleLogin = `-- name: ConsumeAppleLogin :exec
DELETE FROM apple_login_challenges WHERE id = $1
`

func (q *Queries) ConsumeAppleLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, consumeAppleLogin, id)
	return err
}

const createAppleExternalIdentity = `-- name: CreateAppleExternalIdentity :exec
INSERT INTO external_identities (account_id, provider, issuer, subject)
VALUES ($1, 'apple', $2, $3)
`

type CreateAppleExternalIdentityParams struct {
	AccountID pgtype.UUID
	Issuer    string
	Subject   string
}

func (q *Queries) CreateAppleExternalIdentity(ctx context.Context, arg CreateAppleExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, createAppleExternalIdentity, arg.AccountID, arg.Issuer, arg.Subject)
	return err
}

const createAppleLoginChallenge = `-- name: CreateAppleLoginChallenge :one
INSERT INTO apple_login_challenges (state_hash, nonce_hash, proof_hash, platform, expires_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateAppleLoginChallengeParams struct {
	StateHash []byte
	NonceHash []byte
	ProofHash []byte
	Platform  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAppleLoginChallenge(ctx context.Context, arg CreateAppleLoginChallengeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAppleLoginChallenge,
		arg.StateHash,
		arg.NonceHash,
		arg.ProofHash,
		arg.Platform,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAppleLoginForUpdate = `-- name: GetAppleLoginForUpdate :one
SELECT proof_hash, subject, email, email_verified FROM apple_login_challenges
WHERE id = $1 AND consumed_at IS NULL AND subject IS NOT NULL AND expires_at > now()
FOR UPDATE
`

type GetAppleLoginForUpdateRow struct {
	ProofHash     []byte
	Subject       pgtype.Text
	Email         pgtype.Text
	EmailVerified bool
}

func (q *Queries) GetAppleLoginForUpdate(ctx context.Context, id pgtype.UUID) (GetAppleLoginForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAppleLoginForUpdate, id)
	var i GetAppleLoginForUpdateRow
	err := row.Scan(
		&i.ProofHash,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}
