// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: federated.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountEmailExists = `-- name: AccountEmailExists :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE lower(email) = lower($1)) AS exists
`

func (q *Queries) AccountEmailExists(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, accountEmailExists, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const consumeGoogleLoginChallenge = `-- name: ConsumeGoogleLoginChallenge :exec
UPDATE federated_login_challenges SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeGoogleLoginChallenge(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, consumeGoogleLoginChallenge, id)
	return err
}

const createFederatedRefreshToken = `-- name: CreateFederatedRefreshToken :one
INSERT INTO session_refresh_tokens (session_id, token_hash, expires_at)
VALUES ($1, $2, now() + interval '30 days')
RETURNING expires_at
`

type CreateFederatedRefreshTokenParams struct {
	SessionID pgtype.UUID
	TokenHash []byte
}

func (q *Queries) CreateFederatedRefreshToken(ctx context.Context, arg CreateFederatedRefreshTokenParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createFederatedRefreshToken, arg.SessionID, arg.TokenHash)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const createFederatedSession = `-- name: CreateFederatedSession :one
INSERT INTO sessions (account_id, token_hash, idle_expires_at, absolute_expires_at)
VALUES ($1, $2, now() + interval '7 days', now() + interval '7 days')
RETURNING id, idle_expires_at
`

type CreateFederatedSessionParams struct {
	AccountID pgtype.UUID
	TokenHash []byte
}

type CreateFederatedSessionRow struct {
	ID            pgtype.UUID
	IdleExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateFederatedSession(ctx context.Context, arg CreateFederatedSessionParams) (CreateFederatedSessionRow, error) {
	row := q.db.QueryRow(ctx, createFederatedSession, arg.AccountID, arg.TokenHash)
	var i CreateFederatedSessionRow
	err := row.Scan(&i.ID, &i.IdleExpiresAt)
	return i, err
}

const createGoogleAccount = `-- name: CreateGoogleAccount :one
INSERT INTO accounts (email, locale, state, username, verified_at)
VALUES ($1, $2, 'verified', $3, now())
RETURNING id
`

type CreateGoogleAccountParams struct {
	Email    string
	Locale   string
	Username string
}

func (q *Queries) CreateGoogleAccount(ctx context.Context, arg CreateGoogleAccountParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createGoogleAccount, arg.Email, arg.Locale, arg.Username)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createGoogleExternalIdentity = `-- name: CreateGoogleExternalIdentity :exec
INSERT INTO external_identities (account_id, provider, issuer, subject)
VALUES ($1, 'google', $2, $3)
`

type CreateGoogleExternalIdentityParams struct {
	AccountID pgtype.UUID
	Issuer    string
	Subject   string
}

func (q *Queries) CreateGoogleExternalIdentity(ctx context.Context, arg CreateGoogleExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, createGoogleExternalIdentity, arg.AccountID, arg.Issuer, arg.Subject)
	return err
}

const createGoogleLoginChallenge = `-- name: CreateGoogleLoginChallenge :one
INSERT INTO federated_login_challenges (provider, nonce_hash, expires_at)
VALUES ('google', $1, $2)
RETURNING id
`

type CreateGoogleLoginChallengeParams struct {
	NonceHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateGoogleLoginChallenge(ctx context.Context, arg CreateGoogleLoginChallengeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createGoogleLoginChallenge, arg.NonceHash, arg.ExpiresAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findGoogleIdentityAccount = `-- name: FindGoogleIdentityAccount :one
SELECT accounts.id, accounts.username
FROM external_identities
JOIN accounts ON accounts.id = external_identities.account_id
WHERE external_identities.issuer = $1 AND external_identities.subject = $2
`

type FindGoogleIdentityAccountParams struct {
	Issuer  string
	Subject string
}

type FindGoogleIdentityAccountRow struct {
	ID       pgtype.UUID
	Username string
}

func (q *Queries) FindGoogleIdentityAccount(ctx context.Context, arg FindGoogleIdentityAccountParams) (FindGoogleIdentityAccountRow, error) {
	row := q.db.QueryRow(ctx, findGoogleIdentityAccount, arg.Issuer, arg.Subject)
	var i FindGoogleIdentityAccountRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const findGoogleIdentityOwner = `-- name: FindGoogleIdentityOwner :one
SELECT account_id FROM external_identities WHERE issuer = $1 AND subject = $2
`

type FindGoogleIdentityOwnerParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) FindGoogleIdentityOwner(ctx context.Context, arg FindGoogleIdentityOwnerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findGoogleIdentityOwner, arg.Issuer, arg.Subject)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const getActiveGoogleChallengeForUpdate = `-- name: GetActiveGoogleChallengeForUpdate :one
SELECT nonce_hash
FROM federated_login_challenges
WHERE id = $1
  AND provider = 'google'
  AND consumed_at IS NULL
  AND expires_at > now()
FOR UPDATE
`

func (q *Queries) GetActiveGoogleChallengeForUpdate(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getActiveGoogleChallengeForUpdate, id)
	var nonce_hash []byte
	err := row.Scan(&nonce_hash)
	return nonce_hash, err
}
