// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                  pgtype.UUID
	Email               string
	Locale              string
	State               string
	Username            string
	CreatedAt           pgtype.Timestamptz
	VerifiedAt          pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	DeletionRequestedAt pgtype.Timestamptz
}

type AccountNotification struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	Kind         string
	TournamentID pgtype.UUID
	ReadAt       pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type EmailVerificationToken struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	TokenHash     []byte
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	ConsumedAt    pgtype.Timestamptz
	InvalidatedAt pgtype.Timestamptz
}

type ExternalIdentity struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Provider  string
	Issuer    string
	Subject   string
	CreatedAt pgtype.Timestamptz
}

type FederatedLoginChallenge struct {
	ID         pgtype.UUID
	Provider   string
	NonceHash  []byte
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

type GoogleRiscEvent struct {
	ID         string
	ReceivedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type LegalAccountAcceptance struct {
	ID               pgtype.UUID
	AccountID        pgtype.UUID
	EmailHash        []byte
	TermsVersion     string
	TermsContentHash []byte
	Source           string
	AcceptedAt       pgtype.Timestamptz
	RetentionUntil   pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type LocalCredential struct {
	AccountID    pgtype.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Match struct {
	ID                pgtype.UUID
	TournamentID      pgtype.UUID
	RoundNumber       int32
	Sequence          int32
	HomeTeamID        pgtype.UUID
	AwayTeamID        pgtype.UUID
	State             string
	HomeScore         pgtype.Int4
	AwayScore         pgtype.Int4
	StageID           pgtype.UUID
	HomeSourceKind    string
	AwaySourceKind    string
	HomeSourceMatchID pgtype.UUID
	AwaySourceMatchID pgtype.UUID
	WinnerTeamID      pgtype.UUID
	HomePenalties     pgtype.Int4
	AwayPenalties     pgtype.Int4
}

type MatchResultChange struct {
	ID                    pgtype.UUID
	MatchID               pgtype.UUID
	ChangedByAccountID    pgtype.UUID
	PreviousHomeScore     pgtype.Int4
	PreviousAwayScore     pgtype.Int4
	HomeScore             int32
	AwayScore             int32
	ChangedAt             pgtype.Timestamptz
	PreviousHomePenalties pgtype.Int4
	PreviousAwayPenalties pgtype.Int4
	HomePenalties         pgtype.Int4
	AwayPenalties         pgtype.Int4
}

type PasswordResetToken struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	TokenHash     []byte
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	ConsumedAt    pgtype.Timestamptz
	InvalidatedAt pgtype.Timestamptz
}

type ReauthenticationTicket struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	SessionID  pgtype.UUID
	TokenHash  []byte
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

type Session struct {
	ID                pgtype.UUID
	AccountID         pgtype.UUID
	TokenHash         []byte
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}

type SessionRefreshToken struct {
	ID         pgtype.UUID
	SessionID  pgtype.UUID
	TokenHash  []byte
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Tournament struct {
	ID                 pgtype.UUID
	OrganizerAccountID pgtype.UUID
	Name               string
	Sport              string
	Format             string
	State              string
	RoundRobinLegs     int16
	PointsForWin       int16
	PointsForDraw      int16
	PointsForLoss      int16
	CreatedAt          pgtype.Timestamptz
	PublishedAt        pgtype.Timestamptz
	LastActivityAt     pgtype.Timestamptz
}

type TournamentAdministrator struct {
	TournamentID pgtype.UUID
	AccountID    pgtype.UUID
	AssignedAt   pgtype.Timestamptz
}

type TournamentChampion struct {
	TournamentID pgtype.UUID
	TeamID       pgtype.UUID
}

type TournamentFollower struct {
	TournamentID pgtype.UUID
	AccountID    pgtype.UUID
	FollowedAt   pgtype.Timestamptz
}

type TournamentStage struct {
	ID             pgtype.UUID
	TournamentID   pgtype.UUID
	Position       int32
	Type           string
	State          string
	CreatedAt      pgtype.Timestamptz
	RoundRobinLegs pgtype.Int2
}

type TournamentTeam struct {
	ID             pgtype.UUID
	TournamentID   pgtype.UUID
	Name           string
	NameNormalized string
	Position       int32
	WithdrawnAt    pgtype.Timestamptz
}
