// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registrations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingRegistration = `-- name: CreatePendingRegistration :one
WITH created_account AS (
    INSERT INTO accounts (email, state, username, expires_at)
    VALUES ($1, 'pending_verification', $2, now() + interval '7 days')
    ON CONFLICT DO NOTHING
    RETURNING id, email
), created_credentials AS (
    INSERT INTO local_credentials (account_id, password_hash)
    SELECT id, $3 FROM created_account
)
INSERT INTO email_verification_tokens (account_id, token_hash, expires_at)
SELECT id, $4, now() + interval '24 hours'
FROM created_account
RETURNING (SELECT email FROM created_account) AS email
`

type CreatePendingRegistrationParams struct {
	Email        string
	Username     string
	PasswordHash string
	TokenHash    []byte
}

func (q *Queries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) (string, error) {
	row := q.db.QueryRow(ctx, createPendingRegistration,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.TokenHash,
	)
	var email string
	err := row.Scan(&email)
	return email, err
}

const isUsernameAvailable = `-- name: IsUsernameAvailable :one
SELECT NOT EXISTS (
    SELECT 1
    FROM accounts
    WHERE username = $1
) AS available
`

func (q *Queries) IsUsernameAvailable(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, isUsernameAvailable, username)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const rotateSessionTokens = `-- name: RotateSessionTokens :one
WITH consumed_refresh AS (
    UPDATE session_refresh_tokens
    SET consumed_at = now()
    WHERE session_refresh_tokens.token_hash = $1
      AND session_refresh_tokens.consumed_at IS NULL
      AND session_refresh_tokens.revoked_at IS NULL
      AND session_refresh_tokens.expires_at > now()
    RETURNING session_id
), rotated_session AS (
    UPDATE sessions
    SET token_hash = $2,
        last_seen_at = now(),
        idle_expires_at = now() + interval '7 days',
        absolute_expires_at = now() + interval '7 days'
    WHERE id = (SELECT session_id FROM consumed_refresh)
      AND revoked_at IS NULL
    RETURNING id, account_id, idle_expires_at
), created_refresh AS (
    INSERT INTO session_refresh_tokens (session_id, token_hash, expires_at)
    SELECT id, $3, now() + interval '30 days'
    FROM rotated_session
    RETURNING expires_at
)
SELECT accounts.id, accounts.username, rotated_session.idle_expires_at, created_refresh.expires_at
FROM rotated_session
JOIN accounts ON accounts.id = rotated_session.account_id
CROSS JOIN created_refresh
`

type RotateSessionTokensParams struct {
	TokenHash   []byte
	TokenHash_2 []byte
	TokenHash_3 []byte
}

type RotateSessionTokensRow struct {
	ID            pgtype.UUID
	Username      string
	IdleExpiresAt pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) RotateSessionTokens(ctx context.Context, arg RotateSessionTokensParams) (RotateSessionTokensRow, error) {
	row := q.db.QueryRow(ctx, rotateSessionTokens, arg.TokenHash, arg.TokenHash_2, arg.TokenHash_3)
	var i RotateSessionTokensRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IdleExpiresAt,
		&i.ExpiresAt,
	)
	return i, err
}

const verifyRegistrationAndCreateSession = `-- name: VerifyRegistrationAndCreateSession :one
WITH consumed_token AS (
    UPDATE email_verification_tokens
    SET consumed_at = now()
    WHERE email_verification_tokens.token_hash = $1
      AND email_verification_tokens.consumed_at IS NULL
      AND email_verification_tokens.invalidated_at IS NULL
      AND email_verification_tokens.expires_at > now()
    RETURNING account_id
), verified_account AS (
    UPDATE accounts
    SET state = 'verified', verified_at = now(), expires_at = NULL
    WHERE id = (SELECT account_id FROM consumed_token)
      AND state = 'pending_verification'
    RETURNING id, username
), revoked_presented_session AS (
    UPDATE sessions
    SET revoked_at = now()
    WHERE sessions.token_hash = $4::bytea
      AND sessions.revoked_at IS NULL
    RETURNING id
), created_session AS (
    INSERT INTO sessions (account_id, token_hash, idle_expires_at, absolute_expires_at)
    SELECT id, $2, now() + interval '7 days', now() + interval '7 days'
    FROM verified_account
    RETURNING id, idle_expires_at
), created_refresh AS (
    INSERT INTO session_refresh_tokens (session_id, token_hash, expires_at)
    SELECT id, $3, now() + interval '30 days'
    FROM created_session
    RETURNING expires_at
)
SELECT verified_account.id, verified_account.username, created_session.idle_expires_at, created_refresh.expires_at
FROM verified_account
CROSS JOIN created_session
CROSS JOIN created_refresh
`

type VerifyRegistrationAndCreateSessionParams struct {
	TokenHash           []byte
	TokenHash_2         []byte
	TokenHash_3         []byte
	PreviousSessionHash []byte
}

type VerifyRegistrationAndCreateSessionRow struct {
	ID            pgtype.UUID
	Username      string
	IdleExpiresAt pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) VerifyRegistrationAndCreateSession(ctx context.Context, arg VerifyRegistrationAndCreateSessionParams) (VerifyRegistrationAndCreateSessionRow, error) {
	row := q.db.QueryRow(ctx, verifyRegistrationAndCreateSession,
		arg.TokenHash,
		arg.TokenHash_2,
		arg.TokenHash_3,
		arg.PreviousSessionHash,
	)
	var i VerifyRegistrationAndCreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IdleExpiresAt,
		&i.ExpiresAt,
	)
	return i, err
}
