// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suggestions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductSuggestion = `-- name: CreateProductSuggestion :one
WITH inserted AS (
    INSERT INTO product_suggestions (account_id, body)
    VALUES ($1::uuid, $2)
    RETURNING id, account_id, body, created_at
)
SELECT
    inserted.id::text AS id,
    accounts.username,
    inserted.body,
    inserted.created_at
FROM inserted
JOIN accounts ON accounts.id = inserted.account_id
`

type CreateProductSuggestionParams struct {
	AccountID pgtype.UUID
	Body      string
}

type CreateProductSuggestionRow struct {
	ID        string
	Username  string
	Body      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateProductSuggestion(ctx context.Context, arg CreateProductSuggestionParams) (CreateProductSuggestionRow, error) {
	row := q.db.QueryRow(ctx, createProductSuggestion, arg.AccountID, arg.Body)
	var i CreateProductSuggestionRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}
